### ISSUE TITLE
Emarlu API World Project Plan

### ISSUE THREAD

**Issue by Emaad-Mir** [nVarap/Emarlu#1]
# Emarlu
Emaad and Varalu's API World

# Purpose of the program: 
- Create a dating app that actually works this time
- Be able to allow people to set up accounts
  - Files for signup.html and setup.html
  - Users enter their name, username, and password in signup.html
  - Users enter their name, gender, likes, and bio in setup.html
  - Upon submitting information, this data will be added to the list in the backend of users and their attributes and will be used to match up users
- Allow people with accounts to match with others
  - match.html file would allow this along with the match class in dater.py
  - match class uses the number of similar points between users in order to find the user their match
- Build our OWN API endpoint using flask in order to CRUDify our program
  - CRUD in daters.py and dater.py files
  - Setup URLs for create, read, update, and delete
  - Used JavaScript fetch to gather the existing data, make a function for the POST (add profile) method

# THREE MAIN FUNCTIONALITIES
- Input information and *login*
  - User will input their name, username, and password (minimum length 5 characters)
  - After signing up/logging into their account, the user will be prompted to type in some info for their dating profile, including name, gender, likes (can input multiple, though we are running into several issues with the likes not showing up right), and their bio (max length 500 words)
- Set up and *match* with people
  - match.html and dater.py will have the functionality for this
  - url will be set up so that it is in the format of the user id number along with the points needed to match them up with someone
- *Look* at another person's profile

# Handling and using Input to Affect output:
- The input of this code is the user inputting or changing parts of their own user profile to better match with those around them
  - User inputting attributes like name, gender, age, likes, etc. will ultimately impact who they match up with
- They also can set parameters for their choice, as a result affecting the output
- It will pull from a database of people, allowing people to select their favorite choice
  - i.e. API endpoint setup in the flask 
  - Upon submitting their profile, that user's information will be added to the list in the backend url
- Should be able to see another person's profile

# Stretch Goals:
- Build a chat environment between the two people
- Be able to change preferences when looking for people (filters)c

FRONTEND
- [x] Create a login page for the users (using HTML or something similar like PHP)
- [x] Allow users to create accounts 
- [x] Allow users to input their age, gender, interests, etc. that will help in picking their match
- [ ] Create a matching page
- [x] Create a profile page that is dynamic for each person based off name and UUID

BACKEND
- [x] Create a database of multiple users
  - [x] Can use old flask template from last year to do this
  - [x] Model folder and API for users on our dating site can follow the same format as the existing APIs for users, covid, etc.  
 - [ ] Input dynamic data via an API we build that updates through sign-ups
- [x] Make attributes that we will base the person's match on (i.e. interests, age, gender, etc.)
- [x] If necessary, use Postman from CSP to make sure that data can be created, removed, updated, and/or deleted without any issues
- [x] Check the database locally to make sure that it works   

LINKING FRONTEND AND BACKEND
- [ ] Create matching page
- [ ] Allow users to search for (?) and look at other peoples' profiles
- [ ] Based on what the user inputs, the website will provide them with a list of people with similar interests, age groups, etc. (which will come from the data set in the backend component of this project) 

STRETCH GOALS (BOTH FRONTEND AND BACKEND)
- [ ] Create a chat environment between the user and their match
- [ ] Allow users (before they input anything) to filter out who they want in their results (using the same attributes created in the backend portion of this project) 
- [ ] Allow users to edit their various statistics, likes, etc.
